# testing python functions

In [5]:
import numpy as np

In [8]:
data = np.load('shabi.npy')
print(data, data.shape)

[[[[[ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]]

   [[ 10.  10.  10.  10.  10.]
    [ 14.  10.  10.  10.  10.]
    [ 16.  10.  10.  10.  10.]
    [ 17.  10.  10.  10.  10.]
    [ 17.  10.  10.  10.  10.]]

   [[ 11.  10.  10.  10.  10.]
    [ 16.  10.  10.  10.  10.]
    [ 18.  10.  10.  10.  10.]
    [ 18.  10.  10.  10.  10.]
    [ 18.  10.  10.  10.  10.]]

   [[ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]]]


  [[[ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]
    [ 10.  10.  10.  10.  10.]]

   [[ 10.  10.  10.  10.  10.]
    [ 14.  10.  10.  10.  10.]
    [ 16.  10.  10.  10.  10.]
    [ 17.  10.  10.  10.  10.]
    [ 17.  10.  10.  10.  10.]]

   [[ 11.  10.  10.  10.  10.]
    [ 16.  10.  10.  10. 

In [10]:
tP_start = np.arange(300, 75000, 200)
tP_end = np.arange(300, 75000, 200)
tE = np.arange(10, 350, 15)
# resistance = np.arange(50, 20000, 50)
resTest = np.array([50])
vOpenSrc = np.arange(0.2, 12, 0.2)

print(tP_start.shape, tP_end.shape, tE.shape, vOpenSrc.shape)

(374,) (374,) (23,) (59,)


In [12]:
tP_end = np.logspace(2.477, 5.176, 20)
tE = np.logspace(1, 2.544, 15)  # 10 - 350
print(tP_end)
print(tE)

[   299.9162519     415.96101721    576.90627548    800.12510047
   1109.71262337   1539.08695746   2134.59648268   2960.52287479
   4106.01992614   5694.73716196   7898.16706376  10954.15665252
  15192.58164575  21070.95455949  29223.81043595  40531.2010894
  56213.6914127   77964.112025   108130.29016761 149968.48355024]
[ 10.          12.89097346  16.61771968  21.42185833  27.61486072
  35.59824367  45.88960143  59.15616342  76.25805326  98.30405407
 126.72349521 163.35892135 210.58555197 271.46527615 349.94516703]


In [24]:
data_5d = np.load('commutation_dataset.npy')
print(max(data_5d.flatten()))
for data_4d in data_5d:
    for d3d in  data_4d:
        

IndentationError: expected an indented block (493113572.py, line 5)

In [30]:
tE = np.logspace(1, 2.544, 15)  # 10 - 350
data_dummy = np.load('commutation_dataset1.npy')
# print(data_dummy)
print(max(data_dummy[:, :, 0, :, :].flatten()))

39.0
